on:
  push:
    branches:
      -main
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: FTP_Deploy_Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: ${{ secrets.ftp_server }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}